###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

# | with some modifications - by Welington Galvão |

version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: laradock-dev-memcached

    mariadb:
      image: mariadb:10.4
      container_name: laradock-dev-mariadb
      working_dir: /app
      volumes:
        - ./app:/app
      environment:
        - MYSQL_ROOT_PASSWORD=galvao
        - MYSQL_DATABASE=app
        - MYSQL_USER=galvao
        - MYSQL_PASSWORD=galvao
      ports:
        - "8082:3306"

    pma:
      image: phpmyadmin/phpmyadmin
      container_name: PHPMyAdmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: galvao
        PHP_UPLOAD_MAX_FILESIZE: 1G
        PHP_MAX_INPUT_VARS: 1G
      restart: always
      ports:
        - "8081:80"
      volumes:
        - ./src/mysql/sessions:/sessions 

    webserver:
      image: nginx:alpine
      container_name: laradock-dev-webserver
      working_dir: /app
      volumes:
          - ./app:/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./logs:/var/log/nginx
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laradock-php
      working_dir: /app
      volumes:
        - ./app:/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

